### ISSUE TITLE
ヘッダー固定機能

### ISSUE THREAD

**Issue by munierujp** [howdy39/q-accelerator#185]
## 概要
ヘッダーはよく使うのにスクロールすると見えなくなってしまうので、ヘッダーが固定機能がほしいです。
実装してよければ僕がつくります（ユーザースタイルシートを作って使用しているので、URLごとに最適化すればいけそうです）。

## 動作イメージ
![qiita com_howdy39_items_e6136b8454099ebfef29 ipad mini](https://user-images.githubusercontent.com/20086673/39044785-22000664-44cc-11e8-9fc9-0f5dd87cc147.png)

## スタイルシート
```css
.st-HeaderContainer {
    position: sticky;
    top: 0;
    z-index: 999;
}

.st-Header {
    position: sticky;
    top: 0;
    z-index: 999;
}

.pt-1 {
    top: calc(1em + 56px);
}

.p-items_toc {
    top: 56px;
}

@media (max-width: 1200px){
    .it-ActionsMobile {
		top: calc(10px + 56px);
    }
}
```
