### ISSUE TITLE
[提案]コードブロックのソフトラップ機能

### ISSUE THREAD

**Issue by yuta0801** [howdy39/q-accelerator#195]
**提案**

記事幅を超えたコードブロックはスクロールバーが表示されますが、コードが縦にも長い場合スクロールしながら読むのは大変なので、ソフトラップ機能を追加してほしいです。
![image](https://user-images.githubusercontent.com/21266306/40400567-a46f53c8-5e7d-11e8-815b-cb38618a5e22.png)

以下のスタイルを適応することで折り返されて表示されます。
```css
div.highlight pre {
    white-space: pre-wrap;
    word-wrap: break-word;
}
```
